name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Build environment
              uses: actions/checkout@v3

            - name: Instal dependencies and tests - PHP 7.4
              uses: php-actions/composer@v6
              with:
                  php_version: "7.4"

            - name: Instal dependencies and tests - PHP 8.1
              uses: php-actions/composer@v6
              with:
                  php_version: "8.1"
